---
  - name: Create a user "{{ uusername }}" which will install docker in hosts admin access
    user: 
      name: {{ uusername }}
      password: {{ upassword | password_hash('sha512') }}
      generate_ssh_key: yes
      groups: admin append=yes
    when:  assigned_role  == "yes"